#!/bin/bash

set -euxo pipefail

# shellcheck source=/dev/null
source /home/iggy/.env

# Is there even the expected target directory?

if [ ! -d /home/iggy/"${WORKSTATION_DST_DIR}" ]; then
    fail-message "The '${WORKSTATION_DST_DIR}' directory doesn't exist. Did you run the 'rsync' command?"
    exit 1
fi

# Mimic the command iggy should have ran, but in a temporary
# directory so we can do a file comparision

TESTDIR=$(mktemp -d)
chown iggy:iggy "${TESTDIR}"

pushd "${TESTDIR}"
sudo -u iggy rsync -av --progress --stats "fileserver:${FILESERVER_SRC_DIR}" "${WORKSTATION_DST_DIR}"

# Now use three rsync options to verify that the directories are identical
#   --dry-run         - don't actually do anything which would touch a file, but-
#   --itemize-changes - print out an itemized list of changes being made to each file
#   --delete          - delete any file in the destination not at the source
#
# If we do that and get no output, the two directories are identical. If you do not
# use the `--delete` option if you have, say, an empty source directory, or files
# missing in the source, then `--itemize-changes` won't show anything because by
# default rsync doesn't delete files.

ITEMIZED=$(mktemp)

# shellcheck disable=SC2024
sudo -u iggy rsync -a \
    --dry-run \
    --itemize-changes \
    --delete \
    "/home/iggy/${WORKSTATION_DST_DIR}" \
    "${WORKSTATION_DST_DIR}" > "${ITEMIZED}"

if [ -s "${ITEMIZED}" ]; then
    fail-message "That doesn't quite look right, did you run the rsync command with the correct options?"
    exit 1
fi
popd

# If we got here, we're good, cleanup
rm -rf "${TESTDIR}"
rm -f "${ITEMIZED}"

exit 0
