#!/bin/bash

set -euxo pipefail

# shellcheck source=/dev/null
source /home/iggy/.env

# In this challenge we are going to demonstrate incremental updates
# We'll do this by copying the files from the fileserver, then deleting
# every file which ends in `.cat`. 

pushd /home/iggy
sudo -u iggy rsync -av --progress --stats "fileserver:${FILESERVER_SRC_DIR}" "${WORKSTATION_DST_DIR}"
find "${WORKSTATION_DST_DIR}" -type f -name '*.cat' -exec rm -f '{}' ';'
popd
