#!/bin/bash

set -euxo pipefail

# shellcheck source=/dev/null
source /home/iggy/.env

pushd /home/iggy
sudo -u iggy rsync -av --progress --stats "fileserver:${FILESERVER_SRC_DIR}" "${WORKSTATION_DST_DIR}"
popd
